image:
  repository: "amazon/aws-efs-csi-driver"
  tag: "v1.4.0"

replicaCount: 2

controller:
  serviceAccount:
    create: true

storageClasses:
    - name: 
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      parameters:
        fileSystemId:
        provisioningMode: efs-ap
        directoryPerms: "700"
        gidRangeStart: "1000" # optional
        gidRangeEnd: "2000" # optional
        basePath: "/dynamic_provisioning" # optional